
from task_tracker import *

MS = 1000000
Args.do_render = True
tracker = TaskTracker()
tracker.set_time(100 * MS)
tracker.new_taskset()
tracker.add_task(0, TaskParams(500 * MS, 500 * MS, 1))
tracker.add_task(1, TaskParams(500 * MS, 500 * MS, 1))
tracker.add_task(2, TaskParams(500 * MS, 500 * MS, 1))
tracker.set_time(110 * MS)
tracker.get_task(0).release(tracker.get_time(), -1)
tracker.set_time(120 * MS)
tracker.get_task(1).release(tracker.get_time(), -1)
tracker.set_time(130 * MS)
tracker.get_task(2).release(tracker.get_time(), -1)
tracker.set_time(150 * MS)
tracker.get_task(0).execute(tracker.get_time(), 0)
tracker.set_time(190 * MS)
tracker.get_task(1).execute(tracker.get_time(), 1)
tracker.set_time(210 * MS)
tracker.get_task(0).preempt(tracker.get_time())
tracker.set_time(250 * MS)
tracker.get_task(1).preempt(tracker.get_time())
tracker.set_time(300 * MS)
tracker.get_task(2).execute(tracker.get_time(), 0)
tracker.set_time(310 * MS)
tracker.get_task(0).execute(tracker.get_time(), 1)
tracker.set_time(370 * MS)
tracker.get_task(0).complete(tracker.get_time())
tracker.set_time(375 * MS)
tracker.get_task(1).execute(tracker.get_time(), 1)
tracker.set_time(400 * MS)
tracker.get_task(2).complete(tracker.get_time())
tracker.set_time(625 * MS)
tracker.get_task(1).abort(tracker.get_time(), is_deadline_overrun=True)
tracker.set_time(1000 * MS)
tracker.complete_taskset()
